/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState, useContext } from 'react'
import styles from '../../styles/Home.module.css'
import Header from '../components/Header'
import axios from 'axios'
import ModalAdd from '../components/ModalAdd'
import ModalContext from '../context/ModalContext'

/* https://my-unsplash-prisma-nextjs.herokuapp.com */
const Home: NextPage = () => {

  const { setImages, images, search }: any = useContext(ModalContext)

  useEffect(() => {
    axios.get('https://my-unsplash-prisma-nextjs.herokuapp.com/api/images/read').then((response) => {
      setImages(response.data.result);      
    })
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[])



  const deleteImage = (id:any) => {
    axios.post(`https://my-unsplash-prisma-nextjs.herokuapp.com/api/images/delete`, {id: id}).then((response) => {
      setImages(response.data.result);      
    })
  }

  
  return (
    <div className="container">
      <Head> 
        <title>My unsplash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />        
      </Head>

      <Header/>

      <section className='galery'>       
          {
            images && images.map((image:any) => {
              if(image.label.includes(search)) {
                  return (
                    <div className='image-wrapper' key={image.id}>
                    <button onClick={() => deleteImage(image.id)} className='button-delete-transparent'>
                      delete
                    </button>
                    <img className='image' src={image.image} alt={image.label} />
                    <p className='label-image'>{image.label}</p>
                  </div>
                  )
              } 
            })
          }
          

      </section>
      
          <ModalAdd/>
     </div>
  )
}

export default Home
